FROM alpine:3.18

ARG PUPPET_RELEASE
ENV PUPPET_RELEASE=${PUPPET_RELEASE:-7}

ARG PUPPETDB_VERSION
ENV PUPPETDB_VERSION=${PUPPETDB_VERSION:-7.14.0}


RUN echo $PUPPETDB_VERSION
RUN echo $PUPPET_RELEASE
