FROM voxpupuli/voxpupuli/voxbox:latest

ARG PUPPET_RELEASE
ENV PUPPET_RELEASE=${PUPPET_RELEASE:-7}

ARG PUPPET_VERSION
ENV PUPPET_VERSION=${PUPPET_VERSION:-7.14.0}

ARG TARGETARCH
ARG BUILDARCH

RUN echo $TARGETARCH
RUN echo $BUILDARCH
