---
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

name: ⚒️ CI

jobs:
  build_docker_image:
    name: 'Built test Docker image'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Build container
        uses: rwaffen/gha-build-and-publish-a-container@debug_publish
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          publish: 'false'
          tags: |
            ci/dummy:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ci/dummy:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  tests:
    needs:
      - build_docker_image
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
