---
name: ⚒️ CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - id: set-matrix
        run: echo "matrix=$(jq -c . build_versions.json)" >> $GITHUB_OUTPUT

  build_test_container:
    name: 'Build test container'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    needs: setup-matrix
    strategy:
      matrix:
        version: ${{ fromJson(needs.setup-matrix.outputs.matrix.version) }}
        release: ${{ fromJson(needs.setup-matrix.outputs.matrix.release) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: |
            ci/dummy-${{ matrix.release }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ci/dummy-${{ matrix.release }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.release }}.sarif'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-${{ matrix.release }}.sarif'

  tests:
    needs:
      - build_test_container
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
