---
on:
  schedule:
    - cron: '* * * * *'

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: File Sync
        uses: netlify/file-sync-action@v1
        with:
          files: '{"betadots/.github#sync/release.yml": ".github/release.yml"}'
          token: ${{ secrets.GITHUB_TOKEN }}
