name: File Sync ♻️

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@main
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            ${{ github.repository_owner }}/.github@main
          FILES: |
            .github/release.yml=.github/release.yml
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
