---
name: ⚒️ Config Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Checkout Config-Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/.github"
          path: upstream

      - name: Sync .github directory
        run: |
          rsync -avz upstream/sync/ .github/
          if [[ $? -eq 0 ]]; then
            rm -rf upstream
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync from org-.github repository"
