---
name: ⚒️ Config Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Checkout Config-Repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/.github"
          path: upstream

      - name: Sync .github directory
        run: |
          rsync -avz upstream/sync/ .github/
          rm -rf upstream

      - name: Check for changes
        id: changes
        run: |
          git status
          if git diff --quiet; then
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.HAS_CHANGES == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch -c sync-config
          git add .
          git commit -m "Sync from config repository"
          git push origin HEAD

      - name: Create Pull Request
        if: steps.changes.outputs.HAS_CHANGES == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            /repos/${{ github.repository }}/pulls \
            -d '{"title":"Sync from config repository","body":"This pull request contains changes synced from the global config repo.","head":"sync-config","base":"main"}'
